"""
empty message

Revisão: e055492c587e
Anterior: aa6d9ca62274
Data de Criação: 2025-04-13 12:13:31.205628
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e055492c587e'
down_revision: str | None = 'aa6d9ca62274'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuaria', sa.Column('ativa', sa.Boolean(), nullable=False))
    op.add_column(
        'usuaria', sa.Column('sysadmin', sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f('ix_usuaria_ativa'), 'usuaria', ['ativa'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuaria_ativa'), table_name='usuaria')
    op.drop_column('usuaria', 'sysadmin')
    op.drop_column('usuaria', 'ativa')
    # ### end Alembic commands ###
