"""
empty message

Revisão: afa17d84c7a6
Anterior: e055492c587e
Data de Criação: 2025-04-13 15:53:56.276205
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'afa17d84c7a6'
down_revision: str | None = 'e055492c587e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'acesso',
        sa.Column('usuaria_id', sa.Integer(), nullable=False),
        sa.Column('comunidade_id', sa.Integer(), nullable=False),
        sa.Column('tipo', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ['comunidade_id'],
            ['comunidade.id'],
            name=op.f('fk_acesso_comunidade_id_comunidade'),
        ),
        sa.ForeignKeyConstraint(
            ['usuaria_id'],
            ['usuaria.id'],
            name=op.f('fk_acesso_usuaria_id_usuaria'),
        ),
        sa.PrimaryKeyConstraint(
            'usuaria_id', 'comunidade_id', name=op.f('pk_acesso')
        ),
    )
    op.create_index(op.f('ix_acesso_tipo'), 'acesso', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acesso_tipo'), table_name='acesso')
    op.drop_table('acesso')
    # ### end Alembic commands ###
