"""
Cria tabela Usuaria.

Revisão: 45cf2fcb4fe9
Anterior: 87d8d563c2e6
Data de Criação: 2025-04-06 16:55:35.109576
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '45cf2fcb4fe9'
down_revision: str | None = '87d8d563c2e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'usuaria',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('senha', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_usuaria_nome'), 'usuaria', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuaria_nome'), table_name='usuaria')
    op.drop_table('usuaria')
    # ### end Alembic commands ###
