"""
Adiciona as tabelas Modelo e Certificado.

Revisão: 87d8d563c2e6
Anterior: 0
Data de Criação: 2025-03-16 17:46:18.525665
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '87d8d563c2e6'
down_revision: str | None = '0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'modelo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('resumo', sa.String(), nullable=False),
        sa.Column('htmlzip', sa.String(length=102400), nullable=False),
        sa.Column(
            'emissora',
            sa.Enum('PyLadies', 'GruPy-SP', native_enum=False),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_modelo_emissora'), 'modelo', ['emissora'], unique=False
    )
    op.create_index(
        op.f('ix_modelo_resumo'), 'modelo', ['resumo'], unique=False
    )
    op.create_table(
        'certificado',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('codigo', sa.String(length=12), nullable=False),
        sa.Column('modelo_id', sa.Integer(), nullable=False),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('conteudo', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ['modelo_id'],
            ['modelo.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_certificado_codigo'), 'certificado', ['codigo'], unique=True
    )
    op.create_index(
        op.f('ix_certificado_data'), 'certificado', ['data'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificado_data'), table_name='certificado')
    op.drop_index(op.f('ix_certificado_codigo'), table_name='certificado')
    op.drop_table('certificado')
    op.drop_index(op.f('ix_modelo_resumo'), table_name='modelo')
    op.drop_index(op.f('ix_modelo_emissora'), table_name='modelo')
    op.drop_table('modelo')
    # ### end Alembic commands ###
