"""
Adiciona tabela Comunidade.

Revisão: aa6d9ca62274
Anterior: 45cf2fcb4fe9
Data de Criação: 2025-04-13 11:26:58.152346
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'aa6d9ca62274'
down_revision: str | None = '45cf2fcb4fe9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comunidade',
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_comunidade')),
    )
    op.create_index(
        op.f('ix_comunidade_nome'), 'comunidade', ['nome'], unique=True
    )
    op.add_column(
        'modelo', sa.Column('comunidade_id', sa.Integer(), nullable=False)
    )
    op.drop_index('ix_modelo_emissora', table_name='modelo')
    op.create_index(
        op.f('ix_modelo_comunidade_id'),
        'modelo',
        ['comunidade_id'],
        unique=False,
    )
    op.create_foreign_key(
        op.f('fk_modelo_comunidade_id_comunidade'),
        'modelo',
        'comunidade',
        ['comunidade_id'],
        ['id'],
    )
    op.drop_column('modelo', 'emissora')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'modelo',
        sa.Column(
            'emissora',
            sa.VARCHAR(length=8),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f('fk_modelo_comunidade_id_comunidade'),
        'modelo',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_modelo_comunidade_id'), table_name='modelo')
    op.create_index('ix_modelo_emissora', 'modelo', ['emissora'], unique=False)
    op.drop_column('modelo', 'comunidade_id')
    op.drop_index(op.f('ix_comunidade_nome'), table_name='comunidade')
    op.drop_table('comunidade')
    # ### end Alembic commands ###
